### ISSUE TITLE
[Info] What is the repository license?

### ISSUE THREAD

**Issue by Whovian9369** [Zarh/ird_tools#3]
Do you have a specific license in mind for this repository?

**Comment by Zarh** [comment]
I think it should be GPLv3 because I took some code under this licence... I don't really know how it's working. Anyway, If i'm not forced by any rules, for the code I wrote it's 100% free.

**Comment by Whovian9369** [comment]
Thanks!
It would probably be a good idea to officially put a GPLv3 `LICENSE` file into the repo, if you are able to verify compatibility with licenses from the other projects that you took code from.

**Comment by Whovian9369** [comment]
Hello! It would be nice to make sure this is dealt with, please! Even if it's not directly an issue, it would still be nice for anyone in the future!
